from zoneinfo import ZoneInfo


SLACK_API = "https://slack.com/api"

NOTION_API = "https://api.notion.com/v1"
NOTION_VERSION = "2026-03-11"

KST = ZoneInfo("Asia/Seoul")

MAX_NOTION_BLOCKS_PER_REQUEST = 100
MAX_NOTION_TEXT_LENGTH = 1900

NOTION_SINGLE_PART_LIMIT_BYTES = 20 * 1024 * 1024
NOTION_PART_BYTES = 10 * 1024 * 1024

DEFAULT_MAX_IMAGE_MB = 200

NOTION_TITLE_PROPERTY = "이름"
NOTION_CHANNEL_PROPERTY = "채널"
NOTION_PERIOD_PROPERTY = "기간"
NOTION_STATUS_PROPERTY = "상태"

NOTION_STATUS_IN_PROGRESS = "진행 중"
NOTION_STATUS_COMPLETE = "완료"
NOTION_STATUS_FAILED = "실패"